# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c62279a5f40f3c9fb5cc4be92fcc3661357023797b4509837df193b0eda6310c46c23a035faf6403b85222394239202b5c72cdbffa15db32216e961edf90680

test:
  secret_key_base: 379b57b0f307851a187cb0082d4a7466bc83b4fc591b5fcee0a02590a93c1202f03265a8604a6203e901f26d62f8e0424bdbfe59c535b861e2e910094bfe8a0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
